theme = "dracula"

[editor]
line-number = "relative"
mouse = false
auto-save = true
bufferline = "multiple"
true-color = true
cursorline = true
color-modes = true
#This is the default setting
#gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-messages = true
