theme = "dracula"

[editor]
line-number = "relative"
mouse = false
auto-save = true
bufferline = "multiple"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
